branches:
  only:
    - master

services:
    - docker

before_install:
    - docker --version

script:
    - centos="polinux/supervisor:centos"
    - alpine="polinux/supervisor:alpine"
    - docker build -t "$centos" centos7
    - docker build -t "$alpine" alpine

    # Start Centos version
    - docker run -d --name supervisor-centos polinux/supervisor:centos
    # Start Alpine version
    - docker run -d --name supervisor-alpine polinux/supervisor:alpine

    # CentOS Tests 
    # Test if supervisord is running
    - docker exec -i supervisor-centos bash -c "ps aux | grep supervisord"
    # Test if supervisorctl is working
    - docker exec -i supervisor-centos bash -c "supervisorctl stop all"
    # Test if we have inotify working
    - docker exec -i supervisor-centos bash -c "inotifywatch -t 1 /home | tee /tmp/out"

    # Alpine Tests
    # Test if supervisord is running
    - docker exec -i supervisor-alpine bash -c "ps aux | grep supervisord"
    # Test if supervisorctl is working
    - docker exec -i supervisor-alpine bash -c "supervisorctl stop all"
    # Test if we have inotify working
    - docker exec -i supervisor-alpine bash -c "inotifywatch -t 1 /home | tee /tmp/out"